### ISSUE TITLE
테스트 서버 새로고침 시 404 에러

### ISSUE THREAD

**Issue by hou27** [Quickchive/Quickchive-frontend#174]
![image](https://user-images.githubusercontent.com/65845941/203682536-dbb4c6f4-594d-4d0c-afbd-053fc044b34d.png)

@oseunghyun 
root url을 제외한 나머지에서 새로고침 시 위 사진과 같이 에러발생합니다!
확인부탁드려요

**Comment by oseunghyun** [comment]
@hou27 네넵 확인 감사합니다!!!

**Comment by oseunghyun** [comment]
수정했습니다!
