### ISSUE TITLE
test 서버에서 oauth 요청이 상용 서버로 가는 이슈

### ISSUE THREAD

**Issue by oseunghyun** [Quickchive/Quickchive-frontend#183]

**Comment by oseunghyun** [comment]
<img width="1452" alt="스크린샷 2022-12-02 오후 9 56 30" src="https://user-images.githubusercontent.com/73734206/205297907-f7fece49-b0eb-42f0-8eeb-a47f8f273948.png">
<img width="1293" alt="스크린샷 2022-12-02 오후 9 57 20" src="https://user-images.githubusercontent.com/73734206/205298068-a10cbd4c-c02a-455a-8550-7c2eeb55dca4.png">

@hou27 
테스트 서버로 요청시 위 에러 뜨는데 아직 등록 안되어서 그런걸까요? 
아래 주소로 요청했습니다!
https://test.hou27.shop/api/oauth/kakao-auth
https://test.hou27.shop/api/oauth/google-auth

**Comment by hou27** [comment]
@oseunghyun 카톡은 등록 누락이었는데 구글은 되어있었어요 혹시 구글 로그인 창 url 전체 보여주실 수 있을까요?

**Comment by oseunghyun** [comment]
@hou27  

https://accounts.google.com/signin/oauth/error/v2?authError=ChVyZWRpcmVjdF91cmlfbWlzbWF0Y2gSwQEK7JWx7J20IEdvb2dsZeydmCBPQXV0aCAyLjAg7KCV7LGF7J2EIOykgOyImO2VmOyngCDslYrquLAg65WM66y47JeQIOyVseyXkCDroZzqt7jsnbjtlaAg7IiYIOyXhuyKteuLiOuLpC4KCuyVsSDqsJzrsJzsnpDrnbzrqbQgR29vZ2xlIENsb3VkIENvbnNvbGXsl5DshJwg66as65SU66CJ7IWYIFVSSeulvCDrk7HroZ3tlZjshLjsmpQuCiAgGm1odHRwczovL2RldmVsb3BlcnMuZ29vZ2xlLmNvbS9pZGVudGl0eS9wcm90b2NvbHMvb2F1dGgyL3dlYi1zZXJ2ZXIjYXV0aG9yaXphdGlvbi1lcnJvcnMtcmVkaXJlY3QtdXJpLW1pc21hdGNoIJADKkMKDHJlZGlyZWN0X3VyaRIzaHR0cHM6Ly9xdWlja2NoaXZlLm5ldGxpZnkuYXBwL21haW4vZ29vZ2xlL3JlZGlyZWN0MrUCCAESwQEK7JWx7J20IEdvb2dsZeydmCBPQXV0aCAyLjAg7KCV7LGF7J2EIOykgOyImO2VmOyngCDslYrquLAg65WM66y47JeQIOyVseyXkCDroZzqt7jsnbjtlaAg7IiYIOyXhuyKteuLiOuLpC4KCuyVsSDqsJzrsJzsnpDrnbzrqbQgR29vZ2xlIENsb3VkIENvbnNvbGXsl5DshJwg66as65SU66CJ7IWYIFVSSeulvCDrk7HroZ3tlZjshLjsmpQuCiAgGm1odHRwczovL2RldmVsb3BlcnMuZ29vZ2xlLmNvbS9pZGVudGl0eS9wcm90b2NvbHMvb2F1dGgyL3dlYi1zZXJ2ZXIjYXV0aG9yaXphdGlvbi1lcnJvcnMtcmVkaXJlY3QtdXJpLW1pc21hdGNo&client_id=321141908890-snitdkd0cgqfjgn5bi1rrqlbps15ut83.apps.googleusercontent.com

**Comment by hou27** [comment]
> @hou27
> 
> https://accounts.google.com/signin/oauth/error/v2?authError=ChVyZWRpcmVjdF91cmlfbWlzbWF0Y2gSwQEK7JWx7J20IEdvb2dsZeydmCBPQXV0aCAyLjAg7KCV7LGF7J2EIOykgOyImO2VmOyngCDslYrquLAg65WM66y47JeQIOyVseyXkCDroZzqt7jsnbjtlaAg7IiYIOyXhuyKteuLiOuLpC4KCuyVsSDqsJzrsJzsnpDrnbzrqbQgR29vZ2xlIENsb3VkIENvbnNvbGXsl5DshJwg66as65SU66CJ7IWYIFVSSeulvCDrk7HroZ3tlZjshLjsmpQuCiAgGm1odHRwczovL2RldmVsb3BlcnMuZ29vZ2xlLmNvbS9pZGVudGl0eS9wcm90b2NvbHMvb2F1dGgyL3dlYi1zZXJ2ZXIjYXV0aG9yaXphdGlvbi1lcnJvcnMtcmVkaXJlY3QtdXJpLW1pc21hdGNoIJADKkMKDHJlZGlyZWN0X3VyaRIzaHR0cHM6Ly9xdWlja2NoaXZlLm5ldGxpZnkuYXBwL21haW4vZ29vZ2xlL3JlZGlyZWN0MrUCCAESwQEK7JWx7J20IEdvb2dsZeydmCBPQXV0aCAyLjAg7KCV7LGF7J2EIOykgOyImO2VmOyngCDslYrquLAg65WM66y47JeQIOyVseyXkCDroZzqt7jsnbjtlaAg7IiYIOyXhuyKteuLiOuLpC4KCuyVsSDqsJzrsJzsnpDrnbzrqbQgR29vZ2xlIENsb3VkIENvbnNvbGXsl5DshJwg66as65SU66CJ7IWYIFVSSeulvCDrk7HroZ3tlZjshLjsmpQuCiAgGm1odHRwczovL2RldmVsb3BlcnMuZ29vZ2xlLmNvbS9pZGVudGl0eS9wcm90b2NvbHMvb2F1dGgyL3dlYi1zZXJ2ZXIjYXV0aG9yaXphdGlvbi1lcnJvcnMtcmVkaXJlY3QtdXJpLW1pc21hdGNo&client_id=321141908890-snitdkd0cgqfjgn5bi1rrqlbps15ut83.apps.googleusercontent.com

아 이미 에러 url이네요

**Comment by hou27** [comment]
@oseunghyun 제가 redirect url에 오타를 낸 것 같아요.. 수정했습니다! 정상 작동하는지 확인해주세요

**Comment by oseunghyun** [comment]
@hou27 이제 잘 됩니다!!👍
