### ISSUE TITLE
상용 서버에서 로그인 풀림

### ISSUE THREAD

**Issue by oseunghyun** [Quickchive/Quickchive-frontend#196]

**Comment by oseunghyun** [comment]
@hou27 정호님 저는 로그인 안 풀리는데 혹시 어떤 상황에서 풀리는지 알려주실 수 있을까요!?

**Comment by oseunghyun** [comment]
상용 서버에서는 안 풀리고 테스트 서버에서 새로고침 시에 풀리는 걸로 확인됨
우선 원인은 기존에 프로필 조회 응답의 상태 코드가 statusCode로 왔었는데 status로 변경되어서 감지가 되지 않았기 때문 같음
-> 변경 했음

**Comment by oseunghyun** [comment]
swyg 배포된 버전이 main 브랜치가 아닌 것 같아서 확인 요청 드리려고 함
(리프레시 토큰이 기존처럼 쿠키에서 다뤄지고 있음)

**Comment by hou27** [comment]
> 상용 서버에서는 안 풀리고 테스트 서버에서 새로고침 시에 풀리는 걸로 확인됨 우선 원인은 기존에 프로필 조회 응답의 상태 코드가 statusCode로 왔었는데 status로 변경되어서 감지가 되지 않았기 때문 같음 -> 변경 했음

지금도 statusCode로 상태코드가 반환되는 걸로 확인돼서 혹시 다시 확인해주실 수 있나요?

**Comment by oseunghyun** [comment]
@hou27 
<img width="339" alt="스크린샷 2023-01-05 오전 11 05 13" src="https://user-images.githubusercontent.com/73734206/210685170-8d1bad35-c620-46cb-af39-21fa850b93e5.png">
아 다시 확인해보니 data로 오는 값에는 정호님말씀대로 statusCode로 반환되고 status도 따로있네요
아예 statusCode가 반환이 안되는 줄 알았어요!
근데 이전에는 잘 됐었는데 갑자기 안 된거 보면 변경이 됐었던건가요?
상용서버도 다시 확인해봤는데 테스트 서버와 똑같이 반환되고 있는데 테스트 서버만 이상했었어서요ㅜ

**Comment by oseunghyun** [comment]
@hou27 근데 정호님은 테스트 서버 말고 상용 서버가 이상하다고 하셨던거 같은데 지금은 괜찮은가요?
잠깐이라도 이상했던거면 뭔가 문제가 있긴 있는걸텐데요....

**Comment by hou27** [comment]
> @hou27 
> 
> <img width="339" alt="스크린샷 2023-01-05 오전 11 05 13" src="https://user-images.githubusercontent.com/73734206/210685170-8d1bad35-c620-46cb-af39-21fa850b93e5.png">
> 
> 아 다시 확인해보니 data로 오는 값에는 정호님말씀대로 statusCode로 반환되고 status도 따로있네요
> 
> 아예 statusCode가 반환이 안되는 줄 알았어요!
> 
> 근데 이전에는 잘 됐었는데 갑자기 안 된거 보면 변경이 됐었던건가요?
> 
> 상용서버도 다시 확인해봤는데 테스트 서버와 똑같이 반환되고 있는데 테스트 서버만 이상했었어서요ㅜ

변경한 적 없는데 이상하네요 ㅠ

**Comment by hou27** [comment]
> @hou27 근데 정호님은 테스트 서버 말고 상용 서버가 이상하다고 하셨던거 같은데 지금은 괜찮은가요?
> 
> 잠깐이라도 이상했던거면 뭔가 문제가 있긴 있는걸텐데요....

지금은 안 풀리더라구요..

**Comment by oseunghyun** [comment]
> > @hou27 근데 정호님은 테스트 서버 말고 상용 서버가 이상하다고 하셨던거 같은데 지금은 괜찮은가요?
> > 잠깐이라도 이상했던거면 뭔가 문제가 있긴 있는걸텐데요....
> 
> 지금은 안 풀리더라구요..

흠 그렇군요ㅋㅋㅋ 다행이긴한데 우선 알겠습니다 감사합니다!!
