### ISSUE TITLE
api 변경사항 반영

### ISSUE THREAD

**Issue by oseunghyun** [Quickchive/Quickchive-frontend#198]
[변경사항 목록]

- [x] api/collections/* 전부 삭제 
- [x] /api/users/load-collections 삭제
- [x] /api/users/load-favorites 의 response 구조 변경(favorite_collections 삭제)

Category Schema 변경
- [x] POST /api/category/update 카테고리 수정 api request body 변경
- [x] POST /api/category/add 카테고리 추가 api request body 변경
- [x] POST /api/contents/add , update 콘텐츠 추가 api request body 변경
- [x] POST /api/contents/update 콘텐츠 정보 수정 api request body 변경

**Comment by oseunghyun** [comment]
@hou27 
<img width="526" alt="스크린샷 2023-01-06 오후 2 57 28" src="https://user-images.githubusercontent.com/73734206/210939570-7ac4b4fd-5d79-41e9-b753-f59c86f163ee.png">

정호님! 궁금한 부분이 있습니당

1. category/add에서 parentId가 세부 카테고리때문에 네이밍을 바꾸신건가요? 기존의 categoryId값을 parentId로 보내면 될까요?
2. category/update 하면 400에러가 발생합니다..! 근데 여기서는 categoryId로 되어있어서 parentId랑 별개의 값으로 가는건지 설명해주심  감사하겠습니다
3. category/delete 하면
<img width="582" alt="스크린샷 2023-01-06 오후 3 19 53" src="https://user-images.githubusercontent.com/73734206/210942305-406bed70-b8c9-4bd5-b67d-81caba1000b9.png">
이렇게 되는데 테스트 계정이라 그런건가요?


사실 기획 확정되면 많이 변경될 것 같긴 한데 우선 반영 상황 공유드립니다!

**Comment by hou27** [comment]
@oseunghyun 
1. 기존의 값이 변경된게 아니라, 새롭게 추가된 값입니다! 그리고 기존에는 아래처럼 categoryName만 받았었어요! 부모 카테고리를 나타내는 값입니다. 변경하고 회의 참석을 못해서 자세히 설명을 못 드렸네요 ㅠ
![image](https://user-images.githubusercontent.com/65845941/210957758-9f474cb8-81dd-4f16-ae03-f7e65021adec.png)
2. parentId는 단순히 부모가 누군지만 나타내는 값이고, 업데이트는 그 대상이 누군지만 식별하면 돼서 categoryId만 넘겨주시면 됩니다. 400에러가 발생하는 건 지금 DB migration 중에 스키마가 변경되면서 기존 카테고리가 다 사라져서 그럴 거에요
3. 2번 답변의 마지막 줄과 같은 이유입니다.

**Comment by hou27** [comment]
![image](https://user-images.githubusercontent.com/65845941/210958797-4b78ca3c-ca89-4da3-8d7c-e77ea61c8d7c.png)
POST /api/category/add 의 request body schema를 보시면 제가 옵션을 이상하게 설정해서 nullable: true라고만 되어있고   
parentId도 필수 값으로 되어있는데, 카테고리를 추가할 때 부모 카테고리가 없는 최상위 카테고리라면 parentId는 빈값으로 넘겨주시면 됩니다. 이건 바로 수정할게요

https://github.com/Quickchive/quickchive-backend/issues/141

**Comment by oseunghyun** [comment]
> ![image](https://user-images.githubusercontent.com/65845941/210958797-4b78ca3c-ca89-4da3-8d7c-e77ea61c8d7c.png) POST /api/category/add 의 request body schema를 보시면 제가 옵션을 이상하게 설정해서 nullable: true라고만 되어있고 parentId도 필수 값으로 되어있는데, 카테고리를 추가할 때 부모 카테고리가 없는 최상위 카테고리라면 parentId는 빈값으로 넘겨주시면 됩니다. 이건 바로 수정할게요
> 
> [Quickchive/quickchive-backend#141](https://github.com/Quickchive/quickchive-backend/issues/141)

네네 설명 감사합니다!
POST /api/category/add 에서 현재는 세부 카테고리 관련 ui 개발되지 않은 상태라 parentId도 보내지 않는 상태로 냅둘게요!

**Comment by oseunghyun** [comment]
@hou27 
콘텐츠 수정에서 카테고리를 변경하면 해당 카테고리로 이동하는게 아니라 새로운 카테고리가 생기고, 그 카테고리로 콘텐츠가 이동되는거 같아요
카테고리 이름을 수정하는 경우에도 간헐적으로 카테고리가 새로 생기는 것 같은데 정확히 어떤 상황에 발생하는지는 잘 모르겠습니다..!

**Comment by hou27** [comment]
> @hou27 
> 
> 콘텐츠 수정에서 카테고리를 변경하면 해당 카테고리로 이동하는게 아니라 새로운 카테고리가 생기고, 그 카테고리로 콘텐츠가 이동되는거 같아요
> 
> 카테고리 이름을 수정하는 경우에도 간헐적으로 카테고리가 새로 생기는 것 같은데 정확히 어떤 상황에 발생하는지는 잘 모르겠습니다..!
> 
> 
> 
> 

이따 확인해보겠습니다!

**Comment by hou27** [comment]
@oseunghyun 위 이슈 확인해주시면 될 것 같아요!
버그 해결했습니다 감사해요 ㅠ

**Comment by oseunghyun** [comment]
> @hou27  위 이슈 확인해주시면 될 것 같아요! 버그 해결했습니다 감사해요 ㅠ
감사합니다ㅎㅎ
